theme: jekyll-theme-cayman
title: Covid Thailand Trends
description: Thailand Covid testing and case data gathered and combined from various sources for others to download or view
image: https://github.com/djay/covidthailand/wiki/tests_all.png
google_analytics: UA-167358587-2
social-network-links:
   github: djay
   twitter: djay75
social:
   name: Dylan Jay
author:
   twitter: djay75
   github: djay
twitter:
  username: djay75
  image: https://github.com/djay/covidthailand/wiki/tests_all.png
  card: summary
show_downloads: true
github:
  zip_url: https://djay.github.io/covidthailand/#downloads
  tar_url: https://djay.github.io/covidthailand/#downloads